### ISSUE TITLE
Analyze datasets

### ISSUE THREAD

**Issue by alexghergh** [MPS-2022-Paper/MPS-2022-Paper#6]
Analyze the 3 datasets that we have so far:
- [ ] the TAWOS dataset (#1)
- [ ] the CVE dataset (#3)
- [ ] the open source projects / features dataset (#4)
